name: Generate Release Notes

on:
  release:
    types: [published]

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # リポジトリの履歴をすべて取得

      - name: Run cargo changelog
        id: changelog
        run: |
          cargo changelog --output CHANGELOG.md --tag-start $(git describe --tags --abbrev=0) 2>&1 | tee changelog.log

      - name: Update Release Notes
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const release = context.payload.release;
            const changelogContent = require("./CHANGELOG.md").toString();
            const body = `## Release Notes\n\`\`\`\n${changelogContent}\n\`\`\``;
            github.rest.issues.create({
              title: `Release ${release.tag_name}`,
              body: body
            });
