name: Rust Release Binary

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            archive: myapp-linux.zip
          - os: macos-latest
            target: x86_64-apple-darwin
            archive: myapp-macos.zip
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            archive: myapp-windows.zip

    runs-on: ${{ matrix.os }}
    name: Build for ${{ matrix.target }}

    steps:
      - uses: actions/checkout@v3

      - uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_NAME: ${{ matrix.archive }}
          TOOLCHAIN_VERSION: stable
          UPLOAD_MODE: release
